### ISSUE TITLE
update `cell_methods`

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-data-request#11]
current `cell_methods` are still invalid for min/max variables (e.g., `tasmax`, `tasmin`).

**Comment by larsbuntemeyer** [comment]
Here is the `taxmin`, `tasmax` cell_methods for monthly frequency:

```json
          "tas": {
              "frequency": "mon", 
              "modeling_realm": "atmos", 
              "standard_name": "air_temperature", 
              "units": "K", 
              "cell_methods": "area: time: mean", 
              "cell_measures": "area: areacella", 
              "long_name": "Near-Surface Air Temperature", 
              "comment": "near-surface (usually, 2 meter) air temperature", 
              "dimensions": "longitude latitude time height2m", 
              "out_name": "tas", 
              "type": "real", 
              "positive": "", 
              "valid_min": "", 
              "valid_max": "", 
              "ok_min_mean_abs": "", 
              "ok_max_mean_abs": ""
          }, 
          "tasmax": {
              "frequency": "mon", 
              "modeling_realm": "atmos", 
              "standard_name": "air_temperature", 
              "units": "K", 
              "cell_methods": "area: mean time: maximum within days time: mean over days", 
              "cell_measures": "area: areacella", 
              "long_name": "Daily Maximum Near-Surface Air Temperature", 
              "comment": "maximum near-surface (usually, 2 meter) air temperature (add cell_method attribute 'time: max')", 
              "dimensions": "longitude latitude time height2m", 
              "out_name": "tasmax", 
              "type": "real", 
              "positive": "", 
              "valid_min": "", 
              "valid_max": "", 
              "ok_min_mean_abs": "", 
              "ok_max_mean_abs": ""
          }, 
          "tasmin": {
              "frequency": "mon", 
              "modeling_realm": "atmos", 
              "standard_name": "air_temperature", 
              "units": "K", 
              "cell_methods": "area: mean time: minimum within days time: mean over days", 
              "cell_measures": "area: areacella", 
              "long_name": "Daily Minimum Near-Surface Air Temperature", 
              "comment": "minimum near-surface (usually, 2 meter) air temperature (add cell_method attribute 'time: min')", 
              "dimensions": "longitude latitude time height2m", 
              "out_name": "tasmin", 
              "type": "real", 
              "positive": "", 
              "valid_min": "", 
              "valid_max": "", 
              "ok_min_mean_abs": "", 
              "ok_max_mean_abs": ""
          }
```

`"maximum within days time: mean over days"`: It's actually the mean over the maximum of the day. That seems to be a special case of a `cell_method` for `tas`....

**Comment by larsbuntemeyer** [comment]
see also: https://github.com/cf-convention/cf-conventions/issues/197

**Comment by larsbarring** [comment]
HI

I just incidentally came across this issue when seening just noted the tables are still wrong (but that I am sure you are aware of). Regarding your comment about `"time: maximum within days time: mean over days`; this is in principle not related to `tas`, even though this is where we most frequently can see it. The CF issue you are linking to is still open and contains links to CMIP6 DRQ (and further to CMIP7 forward look by Martin). From checking just one random CMIP6 tasmax file it seems that they do not impose the "climatology" attribute for the time axis (which is quite reasonable in my personal opinion).

**Comment by larsbuntemeyer** [comment]
@larsbarring Thanks for reminding me here! Yes, I also have never really seen the `climatology` keyword, e.g., in `tasmin` or `tasmax` climatologies from CMIP6 models (but just checked randomly). 

But that reminds me, that we actually have another case (in CORDEX), since also `prhmax` is requested for daily and monthl frequencies. So i should check:
* `day`: `area: mean time: mean within hours time: maximum over hours`
* `mon`: `area: mean time: mean within hours time: maximum over hours`

**Comment by larsbuntemeyer** [comment]
still missing correct cell_methods for fx variables...

**Comment by gnikulin** [comment]
https://github.com/cf-convention/cf-conventions/issues/197 is very long discussion but without any clear decision. I wouldn't use the "climatology" attribute for monthly mean tasmax and tasmin because there is no any climatology here. Using the "climatology" attribute may also lead to confusions for users who can ask what kind of climatology is it? These structures like `time: minimum within days time: mean over days` have been used in CMIP5/6 and CORDEX-CMIP5 and I've never heard about any problem with them or any complains from users. I would suggest to use them for consistency with CMIP6, although some variables are not presented in CMIP.  We have 7 monthly mean variables - `tasmax`, `tasmin`, `prhmax`, ´sfcWindmax`, `CAPEmax`, `LImax`, `CINmax`.
