### ISSUE TITLE
remove `Pt` suffix from frequencies

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-data-request#24]
this was decided in our google docs discussion, we use, e.g., `6hr` for `mean` and `point` values, there will no `6hrPt` in CORDEX.

**Comment by gnikulin** [comment]
Yes, this "Pt" suffix is a CMIP6 feature if variables should be provided as both mean and average values. Currently, in the CORDEX-CMIP6 Data Request there are no variables that have been requested as both mean and average values.
