### ISSUE TITLE
inconsistent `long_name` attribute for `od550aer`

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-data-request#6]
The CORDEX data request for `od550aer` has an inconsistent `long_name` attribute, e.g.
```
out_name: od550aer
long_name: atmosphere_optical_thickness_due_to_ambient_aerosol_particles
```
is inconsistent with CMIP6 (e.g., `CMIP6_AERday.json`):
```
out_name: od550aer
long_name: Ambient Aerosol Optical Thickness at 550nm
```
That seems to be some error from copying the `standard_name` attribute to the `long_name` attribute...

**Comment by larsbuntemeyer** [comment]
I will simply copy this from CMIP6, that should do it.

**Comment by gnikulin** [comment]
also fixed in the CORDEX-CMIP6 Atmos VL (https://cordex.org/experiment-guidelines/cordex-cmip6/data-request/)

**Comment by larsbuntemeyer** [comment]
thanks! I will rerun the data request table creation then!
